/**
 * Las 100 palabras colgadero del operador (§7.3 del brief,
 * agent_docs/seeds/colgadero-100.md). Dato del usuario, ya validado
 * fonéticamente — no se modifica ni se completa por iniciativa propia.
 */
export interface PalabraColgadero {
  numero: number;
  palabra: string;
}

export const COLGADERO_100: PalabraColgadero[] = [
  { numero: 1, palabra: 'Tea' },
  { numero: 2, palabra: 'Noé' },
  { numero: 3, palabra: 'Amo' },
  { numero: 4, palabra: 'Oca' },
  { numero: 5, palabra: 'Ley' },
  { numero: 6, palabra: 'Oso' },
  { numero: 7, palabra: 'Fea' },
  { numero: 8, palabra: 'Hucha' },
  { numero: 9, palabra: 'Ave' },
  { numero: 10, palabra: 'Torre' },
  { numero: 11, palabra: 'Teta' },
  { numero: 12, palabra: 'Tina' },
  { numero: 13, palabra: 'Tomo' },
  { numero: 14, palabra: 'Taco' },
  { numero: 15, palabra: 'Tela' },
  { numero: 16, palabra: 'Tez' },
  { numero: 17, palabra: 'Tufo' },
  { numero: 18, palabra: 'Techo' },
  { numero: 19, palabra: 'Tubo' },
  { numero: 20, palabra: 'Nuera' },
  { numero: 21, palabra: 'Nido' },
  { numero: 22, palabra: 'Niño' },
  { numero: 23, palabra: 'Nomo' },
  { numero: 24, palabra: 'Eunuco' },
  { numero: 25, palabra: 'Nilo' },
  { numero: 26, palabra: 'Nuez' },
  { numero: 27, palabra: 'Naife' },
  { numero: 28, palabra: 'Nicho' },
  { numero: 29, palabra: 'Nube' },
  { numero: 30, palabra: 'Mar' },
  { numero: 31, palabra: 'Mito' },
  { numero: 32, palabra: 'Mono' },
  { numero: 33, palabra: 'Mamá' },
  { numero: 34, palabra: 'Meca' },
  { numero: 35, palabra: 'Miel' },
  { numero: 36, palabra: 'Mesa' },
  { numero: 37, palabra: 'Mufa' },
  { numero: 38, palabra: 'Mecha' },
  { numero: 39, palabra: 'Mapa' },
  { numero: 40, palabra: 'Carro' },
  { numero: 41, palabra: 'Codo' },
  { numero: 42, palabra: 'Cuna' },
  { numero: 43, palabra: 'Cama' },
  { numero: 44, palabra: 'Coco' },
  { numero: 45, palabra: 'Cola' },
  { numero: 46, palabra: 'Cazo' },
  { numero: 47, palabra: 'Café' },
  { numero: 48, palabra: 'Coche' },
  { numero: 49, palabra: 'Cubo' },
  { numero: 50, palabra: 'Lira' },
  { numero: 51, palabra: 'Loto' },
  { numero: 52, palabra: 'Luna' },
  { numero: 53, palabra: 'Lima' },
  { numero: 54, palabra: 'Loco' },
  { numero: 55, palabra: 'Lulú' },
  { numero: 56, palabra: 'Lazo' },
  { numero: 57, palabra: 'Lofio' },
  { numero: 58, palabra: 'Lucha' },
  { numero: 59, palabra: 'Lupa' },
  { numero: 60, palabra: 'Suero' },
  { numero: 61, palabra: 'Sota' },
  { numero: 62, palabra: 'Zona' },
  { numero: 63, palabra: 'Sima' },
  { numero: 64, palabra: 'Saco' },
  { numero: 65, palabra: 'Sol' },
  { numero: 66, palabra: 'Seso' },
  { numero: 67, palabra: 'Sofá' },
  { numero: 68, palabra: 'Acecho' },
  { numero: 69, palabra: 'Sapo' },
  { numero: 70, palabra: 'Faro' },
  { numero: 71, palabra: 'Foto' },
  { numero: 72, palabra: 'Fauna' },
  { numero: 73, palabra: 'Fama' },
  { numero: 74, palabra: 'Foca' },
  { numero: 75, palabra: 'Fiel' },
  { numero: 76, palabra: 'Fosa' },
  { numero: 77, palabra: 'Fofo' },
  { numero: 78, palabra: 'Ficha' },
  { numero: 79, palabra: 'Fobia' },
  { numero: 80, palabra: 'Chorro' },
  { numero: 81, palabra: 'Choto' },
  { numero: 82, palabra: 'Chino' },
  { numero: 83, palabra: 'Chama' },
  { numero: 84, palabra: 'Cheque' },
  { numero: 85, palabra: 'Chal' },
  { numero: 86, palabra: 'Choza' },
  { numero: 87, palabra: 'Chafa' },
  { numero: 88, palabra: 'Chacha' },
  { numero: 89, palabra: 'Chapa' },
  { numero: 90, palabra: 'Burra' },
  { numero: 91, palabra: 'Pito' },
  { numero: 92, palabra: 'Pino' },
  { numero: 93, palabra: 'Puma' },
  { numero: 94, palabra: 'Vaca' },
  { numero: 95, palabra: 'Bala' },
  { numero: 96, palabra: 'Buzo' },
  { numero: 97, palabra: 'Befo' },
  { numero: 98, palabra: 'Bache' },
  { numero: 99, palabra: 'Pipa' },
  { numero: 100, palabra: 'Torero' },
];
